name: Release kernel
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

jobs:
  build:
    name: Release kernel
    uses: ./.github/workflows/build_kernel.yml

  releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
           merge-multiple: true
           path: /home/runner

      - name: Set build date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{steps.date.outputs.date}}"
          tag_name: "${{steps.date.outputs.date}}"
          prerelease: false
          files: /home/runner/Exynos9611-AOSP_*.zip